scorecard:
  # Setting a global scorecard option
  output: json
  plugins:
    # `basic` tests configured to test 2 CRs
    - basic:
        cr-manifest:
          - "deploy/crds/vdb_from_ddl.yaml"
    # `olm` tests configured to test 2 CRs
    - olm:
        cr-manifest:
          - "deploy/crds/vdb_from_ddl.yaml"
        csv-path: "deploy/olm-catalog/teiid/0.2.0-SNAPSHOT/teiid.v0.2.0-SNAPSHOT.clusterserviceversion.yaml"
