// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/teiid/teiid-operator/pkg/apis/teiid/v1alpha1.VirtualDatabase":       schema_pkg_apis_teiid_v1alpha1_VirtualDatabase(ref),
		"github.com/teiid/teiid-operator/pkg/apis/teiid/v1alpha1.VirtualDatabaseSpec":   schema_pkg_apis_teiid_v1alpha1_VirtualDatabaseSpec(ref),
		"github.com/teiid/teiid-operator/pkg/apis/teiid/v1alpha1.VirtualDatabaseStatus": schema_pkg_apis_teiid_v1alpha1_VirtualDatabaseStatus(ref),
	}
}

func schema_pkg_apis_teiid_v1alpha1_VirtualDatabase(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "VirtualDatabase is the Schema for the virtualdatabases API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/teiid/teiid-operator/pkg/apis/teiid/v1alpha1.VirtualDatabaseSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/teiid/teiid-operator/pkg/apis/teiid/v1alpha1.VirtualDatabaseStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/teiid/teiid-operator/pkg/apis/teiid/v1alpha1.VirtualDatabaseSpec", "github.com/teiid/teiid-operator/pkg/apis/teiid/v1alpha1.VirtualDatabaseStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_teiid_v1alpha1_VirtualDatabaseSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "VirtualDatabaseSpec defines the desired state of VirtualDatabase",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_teiid_v1alpha1_VirtualDatabaseStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "VirtualDatabaseStatus defines the observed state of VirtualDatabase",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
