apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dv-operator
rules:
  - apiGroups:
      - console.openshift.io
    resources:
      - consoleyamlsamples
    verbs:
      - create
      - delete
      - get
