package defaults

// ***********************
//  DO NOT EDIT THIS FILE
// ***********************

const (
	// Version --
	Version = "0.0.1-SNAPSHOT"

	// RuntimeVersion --
	RuntimeVersion = "0.0.1"

	// BaseImage --
	BaseImage = "fabric8/s2i-java:3.0-java8"

	// LocalRepository --
	LocalRepository = "/tmp/artifacts/m2"

	TeiidVersion = "1.1.0-SNAPSHOT"

	SpringBootVersion = "2.1.2.RELEASE"
)
