apiVersion: teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: dv-ftp
spec:
  replicas: 1
  datasources:
    - name: mysite
      type: ftp
      properties:
        - name: username
          value: user
        - name: password
          value: mypassword
        - name: host
          value: ftp.myhost.com
        - name: parent-directory
          value: /path/to/dir
  build:
    source:
      ddl: |
        CREATE DATABASE sample;
        USE DATABASE sample;

        CREATE SERVER mysite FOREIGN DATA WRAPPER ftp;
        CREATE SCHEMA marketdata SERVER mysite;
        CREATE VIRTUAL SCHEMA teiid;

        SET SCHEMA marketdata;
        IMPORT FROM SERVER mysite INTO marketdata;

        SET SCHEMA teiid;

        CREATE VIEW stock_price (
          symbol string(255) NOT NULL AUTO_INCREMENT,
          price double NOT NULL,
          PRIMARY KEY(symbol)
        )
        AS
        SELECT tt.symbol, tt.price
          FROM (EXEC marketdata.getTextFiles('data.txt')) AS f,
          TEXTTABLE(f.file COLUMNS symbol string, price double  HEADER) AS tt;
