apiVersion: teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: matexample
spec:
  replicas: 1
  build:
    source:
      ddl: |
        CREATE DATABASE "matexample";
        USE DATABASE "matexample";

        CREATE SERVER web FOREIGN DATA WRAPPER rest;
        CREATE SCHEMA vix_source SERVER web;

        CREATE VIRTUAL SCHEMA vix_virt;

        IMPORT FROM server web into vix_source;

        SET SCHEMA vix_virt;

        CREATE VIEW vix (
            "date" date primary key,
            "open" double,
            "high" double,
            "low" double,
            "close" double,
            MA10 double
        ) OPTIONS (MATERIALIZED 'TRUE') AS
            select t.*, AVG("close") OVER (ORDER BY "date" ASC ROWS 9 PRECEDING) AS MA10 from
              (call vix_source.invokeHttp(action=>'GET', endpoint=>'https://datahub.io/core/finance-vix/r/vix-daily.csv')) w,
              texttable(to_chars(w.result, 'ascii') COLUMNS "date" date, "open" HEADER 'Vix Open' double, "high" HEADER 'Vix High' double, "low" HEADER 'Vix Low' double, "close" HEADER 'Vix Close' double HEADER) t;
