apiVersion: teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: example
spec:
  replicas: 1
  expose:
    - LoadBalancer
  datasources:
    - name: cephstore
      type: s3
      properties:
        - name: accesskey
          value: xxxx
        - name: bucket
          value: xxx
        - name: region
          value: us-east-1
        - name: secretkey
          value: xxx
  build:
    source:
      ddl: |
        CREATE DATABASE example;
        USE DATABASE example;

        CREATE FOREIGN DATA WRAPPER "user-s3" TYPE s3;  
        CREATE SERVER cephstore FOREIGN DATA WRAPPER "user-s3";
        CREATE SCHEMA ceph SERVER cephstore;
        CREATE VIRTUAL SCHEMA testing;

        SET SCHEMA ceph;
        IMPORT FROM SERVER cephstore INTO ceph;

        SET SCHEMA testing;

        CREATE VIEW sample(
          symbol string,
          price double,
          PRIMARY KEY(symbol)
        ) AS
        SELECT tt.symbol, tt.price,
        FROM 
          (EXEC testing.getTextFiles('sample_data.csv')) AS f, 
          TEXTTABLE(f.file COLUMNS symbol string, price double  HEADER) AS tt;        
